import type { DriverSessionManager } from "../session-manager.js";
import { z } from "zod";
export declare const DRIVER_COMMAND_NAMES: readonly ["back", "click", "cursor", "eval", "fill", "forward", "get", "highlight", "is", "key", "mouse.click", "mouse.drag", "mouse.hover", "mouse.scroll", "network.clear", "network.off", "network.on", "network.path", "open", "reload", "screenshot", "select", "snapshot", "tab.close", "tab.list", "tab.new", "tab.switch", "type", "upload", "viewport", "wait"];
export declare const DriverCommandNameSchema: z.ZodEnum<{
    type: "type";
    fill: "fill";
    is: "is";
    viewport: "viewport";
    select: "select";
    get: "get";
    cursor: "cursor";
    key: "key";
    wait: "wait";
    open: "open";
    back: "back";
    click: "click";
    eval: "eval";
    forward: "forward";
    highlight: "highlight";
    "mouse.click": "mouse.click";
    "mouse.drag": "mouse.drag";
    "mouse.hover": "mouse.hover";
    "mouse.scroll": "mouse.scroll";
    "network.clear": "network.clear";
    "network.off": "network.off";
    "network.on": "network.on";
    "network.path": "network.path";
    reload: "reload";
    screenshot: "screenshot";
    snapshot: "snapshot";
    "tab.close": "tab.close";
    "tab.list": "tab.list";
    "tab.new": "tab.new";
    "tab.switch": "tab.switch";
    upload: "upload";
}>;
export type DriverCommandName = z.infer<typeof DriverCommandNameSchema>;
export type DriverCommandHandler = (manager: DriverSessionManager, params: unknown) => Promise<unknown>;
export type DriverCommandHandlers = Partial<Record<DriverCommandName, DriverCommandHandler>>;
