FROM node:20-alpine AS base

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY apps/web/package*.json ./apps/web/
COPY packages/ ./packages/
COPY plugins/ ./plugins/

RUN npm install

COPY apps/web ./apps/web

EXPOSE 3000

CMD ["npm", "run", "dev", "--workspace=@autoapply/web"]
