FROM node:20-alpine AS base

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY prisma ./prisma/
COPY apps/api/package*.json ./apps/api/
COPY packages/ ./packages/

RUN npm install

COPY apps/api ./apps/api

EXPOSE 4000

CMD ["npm", "run", "dev", "--workspace=@autoapply/api"]
