FROM node:20-alpine AS base

WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY prisma ./prisma/
COPY apps/workers/package*.json ./apps/workers/
COPY packages/ ./packages/
COPY plugins/ ./plugins/

RUN npm install

COPY apps/workers ./apps/workers

EXPOSE 4001

CMD ["npm", "run", "dev", "--workspace=@autoapply/workers"]
